name: Build and Deploy WebGL

on:
  push:
    branches:
      - Main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout del código fuente
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cachear la carpeta Library
      - name: Cache Unity Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-WebGL
          restore-keys: Library-

      # Construir el proyecto en WebGL
      - name: Build Unity Project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL

      # Desplegar en GitHub Pages
      - name: Deploy to GitHub Pages
        run: |
          BUILD_DIR=build/WebGL
          GH_PAGES_BRANCH=gh-pages

          # Configurar Git
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Verificar si existe la rama gh-pages
          if git ls-remote --exit-code --heads origin $GH_PAGES_BRANCH; then
            # Clonar la rama existente
            git clone --branch $GH_PAGES_BRANCH https://github.com/${{ github.repository }}.git deploy
          else
            # Crear nuevo repositorio para gh-pages
            mkdir deploy
            cd deploy
            git init
            git remote add origin https://github.com/${{ github.repository }}.git
            git checkout --orphan $GH_PAGES_BRANCH
            cd ..
          fi

          # Limpiar directorio y copiar archivos
          cd deploy
          rm -rf * .gitignore .gitmodules || true
          cp -r $GITHUB_WORKSPACE/$BUILD_DIR/* .

          # Mover contenido de WebGL a la raíz si es necesario
          if [ -d WebGL ]; then
            mv WebGL/* .
            rmdir WebGL
          fi

          # Hacer commit y push
          git add -A
          git commit -m "Deploy WebGL build from ${{ github.sha }}"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git $GH_PAGES_BRANCH
