name: Build and Deploy Windows Standalone

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  buildAndRelease:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache Unity Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-WindowsStandalone-${{ runner.os }}-${{ hashFiles('**/ProjectSettings/ProjectVersion.txt') }}

      - name: Build Unity Project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64

      - name: Deploy to Build Branch
        run: |
          BUILD_DIR=$GITHUB_WORKSPACE/build/StandaloneWindows64
          BUILD_BRANCH=build-branch

          if [ ! -d "$BUILD_DIR" ]; then
            echo "Error: Directory $BUILD_DIR does not exist."
            exit 1
          fi

          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          DEPLOY_DIR=$(mktemp -d)
          mkdir -p $DEPLOY_DIR
          cp -r $BUILD_DIR/* $DEPLOY_DIR/

          cd $DEPLOY_DIR
          git init
          git checkout --orphan $BUILD_BRANCH
          git add .
          git commit -m "Deploy build from commit ${{ github.sha }}"
          git push --force https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} $BUILD_BRANCH

      - name: Create Release Artifact
        run: |
          BUILD_DIR=$GITHUB_WORKSPACE/build/StandaloneWindows64
          ZIP_FILE=$GITHUB_WORKSPACE/StandaloneWindows64.zip

          if [ ! -d "$BUILD_DIR" ]; then
            echo "Error: Directory $BUILD_DIR does not exist."
            exit 1
          fi

          cd $BUILD_DIR
          zip -r $ZIP_FILE . || { echo "Failed to create ZIP file"; exit 1; }

      - name: Upload Release to GitHub
        uses: ncipollo/release-action@v1
        with:
          tag: "build-${{ github.sha }}"
          name: "Windows Standalone Build"
          body: "Build creada a partir del commit ${{ github.sha }}."
          files: $GITHUB_WORKSPACE/StandaloneWindows64.zip
          draft: false
          prerelease: false
